name: 🚀 Run

on:
  pull_request:
    types: [opened, reopened]

jobs:
  run:
    name: 🚀 Run
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install
        shell: bash
        run: pip3 install pytest

      - name: 🚀 Run
        shell: bash
        run: |
          python3 main.py
          pytest
